version: "3.8"

services:
  atlas:
    build: .
    ports:
      - "4000:4000"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - TZ=America/Los_Angeles
    restart: unless-stopped
